### ISSUE TITLE
文件流关闭报段错误？

### ISSUE THREAD

**Issue by ghost** [shukean/monip#6]
您好，我在您的代码基础上做了修改，将文件流在PHP_MINIT阶段打开，然后再关闭，会直接报段错误，我发现在PHP_MINIT阶段打开的文件流不需要手动关闭，是不是在PHP_MSHUTDOWN阶段，php替我清理了，这个问题找不到具体依据，麻烦帮忙解答一下，谢谢！

**Comment by shukean** [comment]
这个可能需要看下php的模块注册和释放这部分.

**Comment by ghost** [comment]
能给简单说下，或者推荐一些准确的资料！

**Comment by shukean** [comment]
先试试gdb 调试看看错误内容吧.

**Comment by ghost** [comment]
zend_list_close (res=0xf6003000) at /home/tar.gz/php-7.1.6/Zend/zend_list.c:85
85	{
(gdb) n
86		if (GC_REFCOUNT(res) <= 0) {
(gdb) 

Program received signal SIGSEGV, Segmentation fault.
zend_list_close (res=0xf6003000) at /home/tar.gz/php-7.1.6/Zend/zend_list.c:86
86		if (GC_REFCOUNT(res) <= 0) {


最终定位到了php_stream_free 中的zend_list_close ()函数    中的(GC_REFCOUNT(res)   这应该是引用计数的问题吧。。但是具体是哪的问题？您能帮忙解释么

**Comment by shukean** [comment]
如果是这里报错, 应该是重复释放资源res的问题,  即该资源res已经不存在了.
