### ISSUE TITLE
有支持datx格式的php5.6版本吗

### ISSUE THREAD

**Issue by lizhenghui** [shukean/monip#7]

**Comment by shukean** [comment]
需要提供datax文件来调试

**Comment by lizhenghui** [comment]
因为目前ipip.net只维护datx格式的免费数据库了（https://www.ipip.net/product/client.html），datx免费数据库可以直接在页面下载，我们线上用的php版本是php5.6, 因为并发量比较大，因此对IP查找性能要求较高，希望能支持php5的datx文件格式，最好是PHP-fpm启动时加载数据库文件，每次读文件比较耗时，我现在也在改，如果改好了到时可以提个PR。

**Comment by shukean** [comment]
已经提供了, 可以切换到分支 datx-php5.x

**Comment by lizhenghui** [comment]
棒棒的，非常感谢！
