### ISSUE TITLE
make报错能帮忙看看吗

### ISSUE THREAD

**Issue by alu12138** [shukean/monip#8]
![image](https://user-images.githubusercontent.com/12081203/45671738-d29fbc00-bb58-11e8-9a12-79eaaf5e92da.png)

**Comment by alu12138** [comment]
php5.6

**Comment by shukean** [comment]
发下  php --version

**Comment by alu12138** [comment]
PHP 5.6.37 (cli) (built: Jul 19 2018 20:06:19) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Comment by shukean** [comment]
尝试加下在 ipip.c 的  #include "php.h" 下新增一行。 
 #include <stdbool.h>

**Comment by alu12138** [comment]
好了，辛苦，谢谢。
